config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 get 'top/index' =>'top#index'
 get 'schedule/index' =>'schedule#index'
 get 'schedule/result20240304' =>'schedule#result20240304'
 get 'schedule/result2024XXXX' =>'schedule#result2024XXXX'

 get 'photos' => 'photos#index'
 get 'photos/new' => 'photos#new'
 post 'photos' =>'photos#create'
 get 'photos/:id' =>'photos#show',as:'photo'

 resources 'photos' 
 root 'top#index'

 get 'members' =>'members#index'
 get 'members/new' =>'members#new'
 post 'members' =>'members#create'
 get 'members/:id' =>'members#show',as:'member'
 patch 'members/:id' =>'members#update'
 delete 'members/:id' =>'members#destroy'
 get 'members/:id/edit' =>'members#edit',as:'edit_member'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, only: [:new, :create]
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
 
    def index
      @members = Member.all
    end

    def new
      @member =Member.new
    end

    def create
      member = Member.new(member_params)
      if member.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

     def show
      @member=Member.find(params[:id])
    end
    

    def edit
      @member=Member.find(params[:id])
    end

    def update
      member=Member.find(params[:id])
      if member.update(member_params)
          redirect_to :action =>"index"
      else
          redirect_to :action => "new"
      end
    end

    def destroy
      member=Member.find(params[:id])
      member.destroy
      redirect_to action: :index
    end

    private
    def member_params
       params.require(:member).permit(:title,:name,:mate) 
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    def index
      @photos = Photo.all
    end

    def new
      @photo =Photo.new
    end

    def create
      photo = Photo.new(photo_params)
      if photo.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
    end

    def show
      @photo=Photo.find(params[:id])
    end

    def edit
      @photo=Photo.find(params[:id])
    end

    def update
      photo=Photo.find(params[:id])
      if photo.update(photo_params)
          redirect_to :action =>"show",:id =>photo.id
      else
          redirect_to :action => "new"
      end
    end

    def destroy
      photo=Photo.find(params[:id])
      photo.destroy
      redirect_to action: :index
    end

   


    private
    def photo_params
       params.require(:photo).permit(:comment, :image) 
    end

end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
  before_action :authenticate_user!, only: [:index, :result20240304]
  def index
  end  

  def result20240304
  end

  def result2024XXXX
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rule_helper.rb
module RuleHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
    
    <body>
      <%= yield %>
    </body>
    
<footer>
    <p>Copyright © NogawaCup All Right Reserved.</p>
</footer>
    
</html>

app/views/members/edit.html.erb
<%= stylesheet_link_tag 'members_new', :media => "all" %>

<header>
</header>
<section id="first-block">
    <div class="bg-image2">
        <div class="bg-inner">
            <div class="upp">
                <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
            </div>

            <div class="main-title">
                チーム登録変更
            </div>
        </div>
    </div>
</section>

<section id="second-block">
    <div class="blue">
        <%= link_to '参加チームを見る', :controller => "members", :action => "index" %>
    </div>

    <div class="post-container">
        <%= form_for @member do |f| %>
            <div class="field">
                <%= f.label :チーム名 %>
                <%= f.text_field:title %>
            </div>

            <div class="field">
                <%= f.label :代表者名 %>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%=f.label :メンバー %>
                <%=f.text_field :mate %>                    
            </div>
            <%= f.submit "編集する" %>  
   
        <% end %>
        <div class='a'>
            <%= button_to "削除",member_path(@member.id), method: :delete %>
        </div>
    </div>
</section>

app/views/members/index.html.erb
<%= stylesheet_link_tag 'members_index', :media => "all" %>
<header>
</header>
<section id="first-block">
  <div class="bg-image2">
    <dv class="bg-inner">
      <div class="upp">
          <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
      </div>

      <div class="main-title">
          参加チーム一覧
      </div>
    </div>
  </div>
</section>

<section id="second-block">
  <div class="blue">
    <a href="members/new" >新規参加登録へ</a>
  </div>

  <div class="post-container"> 
      <div class="title">
        <div class="team">
          チーム名
        </div>
        <div class="name">
          代表者名
        </div>
        <div class="member">
          メンバー
        </div>
        <div>
          
        </div>
      </div>

      <% @members.each do |t| %>
        <div class="post">
          <div class="team">
            <%=t.title %>
          </div>
          <div class="name">
            <%=t.name %>
          </div>
          <div class="member">
            <%=t.mate %>
          </div>
          
          <div class="edit"> 
            <%= link_to "編集", edit_member_path(t.id) %>  
          </div>
      
        </div>
      <% end %>
  </div>     
</section>




  
  

app/views/members/new.html.erb
<%= stylesheet_link_tag 'members_new', :media => "all" %>

<header>
</header>
<section id="first-block">
    <div class="bg-image3">
        <div class="bg-inner">
            <div class="upp">
                <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
            </div>

            <div class="main-title">
                新規参加登録
            </div>
        </div>
    </div>
</section>

<section id="second-block">
    <div class="blue">
        <%= link_to '参加チームを見る', :controller => "members", :action => "index" %>
    </div>

    <div class="post-container">
        <%= form_for @member do |f| %>
            <div class="field">
                <%= f.label :チーム名 %>
                <%= f.text_field:title %>
            </div>

            <div class="field">
                <%= f.label :代表者名 %>
                <%= f.text_field :name %>
            </div>

            <div class="field">
                <%=f.label :メンバー %>
                <%=f.text_field :mate %>                    
            </div>
            <%= f.submit "参加登録",class:"register" %>
        <% end %>
    </div>
</section>
    


        

app/views/members/show.html.erb
<%= stylesheet_link_tag 'members_new', :media => "all" %>

<header>
</header>
<section id="first-block">
    <div class="upp">
        <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
    </div>

    <div class="main-title">
        参加チーム一覧
    </div>
</section>

<section id="second-block">
    <div class="blue">
        <%= link_to '参加チームを見る', :controller => "members", :action => "index" %>
    </div>

<section id="third-block">
<div class="member">
  <p><%= @member.title %></p>
  <p><%= @member.name %></p>
  <p><%= @member.mate %></p>
</div>
<%= button_to "編集", edit_member_path(@member.id) %>  
<%= button_to "削除",member_path(@member.id), method: :delete %>


</section>

app/views/photos/edit.html.erb
<%= stylesheet_link_tag 'photos_new',:media=>"all" %>

<header>
</header>
<section id="first-block">
  <div class="bg-image5">
    <div class="bg-inner">
      <div class="upp">
          <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
      </div>

      <div class="main-title">
          画像一覧
      </div>
    </div>
  </div>
</section>

<section id="second-block">
  <div class="blue">
    <%= link_to '画像一覧へ', :controller => "photos", :action => "index" %>
  </div>

  <div class="post-container">
    
    <%= form_for @photo do |f| %>
        <div class="field">
          <div class="label-box__inner">
            <label class="mealpicture">写真をアップロード
              <%= f.file_field :image ,class:"input-default" %>
            <div class="boxFileSelect"></div>
            </label>
          </div>
        </div>

        <div class="field">
          <%= f.label :コメント %>
          <%= f.text_field :comment, :size=>140%>
        </div>

        <div class="edit-2">  
           <%= f.submit "編集する" %> 
        </div>
    <% end %>
    <%=button_to '削除する',photo_path(@photo.id), method: :delete %>
  </div>
</section>

app/views/photos/index.html.erb
<%= stylesheet_link_tag 'photos_index', :media => "all" %>

<header>
</header>
<section id="first-block">
  <div class="bg-image4">
    <div class="bg-inner">
      <div class="upp">
          <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
      </div>

      <div class="main-title">
          画像一覧
      </div>
    </div>
  </div>
</section>

<section id="second-block">
  <div class="blue">
    <a href="photos/new" >投稿ページへ</a>
  </div>

  <div class="post-container">
      <% @photos.each do |t| %>
        <div class="post">
          <div class="main-box">
            <div class="left-conteiner">
              <%= image_tag t.image_url, size: "400x400" if t.image? %>
            </div>     

            <div class="right-container">
              <div>
                <%=t.comment %>
              </div>
              <div class="edit">
                <%=link_to '詳細へ',photo_path(t.id) %>
              </div>
              <div class="edit">
                <%=link_to '編集する',edit_photo_path(t.id) %>
              </div>
              
              <div>
                <%= t.created_at %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</section>

app/views/photos/new.html.erb
<%= stylesheet_link_tag 'photos_new',:media=>"all" %>

<header>
</header>
<section id="first-block">
  <div class="bg-image5">
    <div class="bg-inner">
      <div class="upp">
          <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
      </div>

      <div class="main-title">
          投稿する
      </div>
    </div>
  </div>
</section>

<section id="second-block">
  <div class="blue">
    <%= link_to '画像一覧へ', :controller => "photos", :action => "index" %>
  </div>

  <div class="post-container">
    
    <%= form_for @photo do |f| %>
        <div class="field">
          <div class="label-box__inner">
            <label class="mealpicture">写真をアップロード
              <%= f.file_field :image ,class:"input-default" %>
            <div class="boxFileSelect"></div>
            </label>
          </div>
        </div>

        <div class="field">
          <%= f.label :コメント %>
          <%= f.text_field :comment, :size=>140%>
        </div>

                  
        <%= f.submit "投稿する" %>
    <% end %>
  </div>
</section>

    

app/views/photos/show.html.erb
<%= stylesheet_link_tag 'photos_index', :media => "all" %>

<header>
</header>
<section id="first-block">
  <div class="bg-image5">
    <div class="bg-inner">
      <div class="upp">
          <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
      </div>

      <div class="main-title">
          画像詳細
      </div>
    </div>
  </div>
</section>

<section id="second-block">
  <div class="blue">
    <a href="photos/new" >投稿ページへ</a>
    <a href="photos">画像一覧へ</a>
  </div>

  <div class="post-container">
    <div class="main-box">
      <div class="left-conteiner">
        <%= image_tag @photo.image_url, size: "300x600" if @photo.image? %>
      </div>     

      <div class="right-container">
        <div>
          <p><%=@photo.comment %></p>
        </div>
      <div>
        <%= @photo.created_at %>
      </div>
      <div class="photo">
          
          
      </div>
    </div>
  </div>
  <div class="edit2">
    <div class="edit3">
      <%= link_to "一覧に戻る", photos_path %>
    </div>
    <div class="edit3">
      <%= link_to "編集する",edit_photo_path(@photo.id) %>
    </div>
  </div>   
</section>

app/views/schedule/index.html.erb
<section id="second-block">
  <div class="about-container">
    <p class="info-text">
      <%= link_to 'schedule', :controller => "schedule", :action => "index" %>
    </p>

    

    <p class="info-text">
      <%= link_to 'Photo', :controller => "photos", :action => "index" %>
    </p>

  </div>
</section>

<section id="third-block">
    <p class="title">
      開催日程
    </p>

    <p class="event-name">
      2024.03.04 第1回大会
      <%= link_to '試合結果', schedule_result20240304_path %>
    </p>

  </div>
<!--  コンテンツはここまで  -->

  <footer>	
  </footer>
</body>

app/views/schedule/result20240304.html.erb
<%= stylesheet_link_tag 'result', :media => "all" %>

<header>
</header>
<section id="first-block">
  2024.3.4 フットサル試合結果
</section>

<div class="game-day">
  
</div>

<section id="second-block">
    <div class="game-list2">
      <a href="#">リーグ1試合結果</a>
      <div class="dropdown__lists2">
        <div class="dropdown__list">鎖骨 2-1 裏拳</div>
        <div class="dropdown__list">IHモ 0-3 佐研</div>
        <div class="dropdown__list">鎖骨 5-0 IHモ</div>
        <div class="dropdown__list">裏拳 2-0 佐研</div>
        <div class="dropdown__list">鎖骨 1-0 佐研</div>
        <div class="dropdown__list">裏拳 2-0 IHモ</div>
      </div>
    </div>

    <table class="table" >
        <tr class="team2">
          <th>チーム名</th>
          <th>鎖骨</th>
          <th>裏拳</th>
          <th>IHモ</th>
          <th>佐研</th>
          <th>勝敗</th>
          <th>順位</th>
        </tr>
        <tr>
          <td class="team2">鎖骨ぽっきんず</td>
          <td class="slash"></td>
          <td class="win">2-1</td>
          <td class="win">5-0</td>
          <td class="win">1-0</td>
          <td class="total">3勝0敗</td>
          <td class="total">1位</td>
        </tr> 
        <tr>
          <td class="team2">裏拳ファイターズ</td>
          <td>1-2</td>
          <td class="slash"></td>
          <td class="win">2-0</td>
          <td class="win">2-0</td>
          <td class="total">2勝1敗</td>
          <td class="total">2位</td>
        </tr>
        <tr>
            <td class="team2">IHモーターズ</td>
            <td>0-5</td>
            <td>0-2</td>
            <td class="slash"></td>
            <td>0-3</td>
            <td class="total">0勝3敗</td>
            <td class="total">4位</td>
        </tr>
        <tr>
            <td class="team2">佐藤研</td>
            <td>0-1</td>
            <td>0-2</td>
            <td class="win">3-0</td>
            <td class="slash"></td>
            <td class="total">1勝2敗</td>
            <td class="total">3位</td>
        </tr>
    </table>
</section>

<section id="second-block">
  <div class="game-list2">
      <a href="#">リーグ2試合結果</a>
      <div class="dropdown__lists2">
        <div class="dropdown__list">戸高 1-1 松板</div>
        <div class="dropdown__list">バ千 3-3.5 Drず</div>
        <div class="dropdown__list">戸高 3.5-1 バ千</div>
        <div class="dropdown__list">松板 4-0 Drず</div>
        <div class="dropdown__list">戸高 2-0 Drず</div>
        <div class="dropdown__list">松板 3.5-0 バ千</div>
      </div>
  </div>

  <table class="table">
    <tr class="team2">
      <th>チーム名</th>
      <th>戸高</th>
      <th>松板</th>
      <th>バ千</th>
      <th>Drず</th>
      <th>勝敗</th>
      <th>順位</th>
    </tr>
    <tr>
      <td class="team2">戸高と愉快に</td>
      <td class="slash"></td>
      <td >1-1</td>
      <td class="win">3.5-1</td>
      <td class="win">2-0</td>
      <td class="total">2勝1分</td>
      <td class="total">2位</td>
    </tr> 
    <tr>
      <td class="team2">松浦板倉研</td>
      <td>1-1</td>
      <td class="slash"></td>
      <td class="win">3.5-0</td>
      <td class="win">4-0</td>
      <td class="total">2勝1分</td>
      <td class="total">1位</td>
    </tr>
    <tr>
        <td class="team2">バモス千葉</td>
        <td>1-3.5</td>
        <td>0-3.5</td>
        <td class="slash"></td>
        <td>3-3.5</td>
        <td class="total">0勝3敗</td>
        <td class="total">4位</td>
    </tr>
    <tr>
        <td class="team2">がんばれDrず</td>
        <td>0-2</td>
        <td>0-4</td>
        <td class="win">3.5-3</td>
        <td class="slash"></td>
        <td class="total">1勝2敗</td>
        <td class="total">3位</td>
    </tr>
  </table>
</section>

<section id="forth-block">
  <div class="game-list2">
    <a href="#">下位トーナメント</a>
    <div class="dropdown__lists2">
      <div class="dropdown__list">佐研 ○-● バ千</div>
      <div class="dropdown__list">Drず ○-● IHモ</div>
      <div class="dropdown__list">３位決定戦</div>
      <div class="dropdown__list">バ千 ○-● IHモ</div>
      <div class="dropdown__list">決勝戦</div>
      <div class="dropdown__list">佐研 ○-● Drず</div>
    </div>
  </div>
  <table class="tournament" cellpadding="0" cellspacing="0">
    <tr>
      <td rowspan="2" class="winner">佐藤研</td>
      <td class="no-line"> </td>
      <td class="no-line"> </td>
      <td class="no-line"> </td>
      <td class="no-line"> </td>
      <td rowspan="2">がんばれDrず</td>
    </tr>
    <tr>
      <td class="top-right-line-winner"> </td>
      <td> </td>
      <td> </td>
      <td class="top-left-line-winner"> </td>
    </tr>
    <tr>
      <td> </td>
      <td class="right-line-winner"> </td>
      <td class="bottom-right-line-winner"> </td>
      <td class="bottom-line"> </td>
      <td class="left-line-winner"> </td>
      <td> </td>
    </tr>
    <tr>
      <td> </td>
      <td class="right-line"> </td>
      <td> </td>
      <td> </td>
      <td class="left-line"> </td>
      <td> </td>
    </tr> 
    <tr>
      <td rowspan="2">バモス千葉</td>
      <td class="bottom-right-line"> </td>
      <td> </td>
      <td> </td>
      <td class="bottom-left-line"> </td>
      <td rowspan="2">IHモーターズ</td>
    </tr>
    <tr>  
      <td class="no-line"> </td>
      <td class="no-line"> </td>
      <td class="no-line"> </td>
      <td class="no-line"> </td> 
    </tr>
  </table>
</section>

<section id="fifth-block">
  <div class="game-list2">
    <a href="#">決勝トーナメント</a>
    <div class="dropdown__lists2">
      <div class="dropdown__list">鎖骨 ○-● 戸高</div>
      <div class="dropdown__list">松板 ○-● 裏拳</div>
      <div class="dropdown__list">3位決定戦</div>
      <div class="dropdown__list">戸高 ●-○ 裏拳</div>
      <div class="dropdown__list">決勝戦</div>
      <div class="dropdown__list">鎖骨 ○-● 松板</div>
    </div>
  </div>
  <table class="tournament" cellpadding="0" cellspacing="0">
  <tr>
    <td rowspan="2" class="winner">鎖骨<br>ぽっきんず</td>
    <td class="no-line"> </td>
    <td class="no-line"> </td>
    <td class="no-line"> </td>
    <td class="no-line"> </td>
    <td rowspan="2">松浦板倉研</td>
  </tr>
  <tr>
    <td class="top-right-line-winner"> </td>
    <td> </td>
    <td> </td>
    <td class="top-left-line"> </td>
  </tr>
  <tr>
    <td> </td>
    <td class="right-line-winner"> </td>
    <td class="bottom-right-line-winner"> </td>
    <td class="bottom-line"> </td>
    <td class="left-line"> </td>
    <td> </td>
  </tr>
  <tr>
    <td> </td>
    <td class="right-line"> </td>
    <td> </td>
    <td> </td>
    <td class="left-line-winner"> </td>
    <td> </td>
  </tr> 
  <tr>
    <td rowspan="2">戸高と愉快に</td>
    <td class="bottom-right-line"> </td>
    <td> </td>
    <td> </td>
    <td class="bottom-left-line-winner"> </td>
    <td rowspan="2">裏拳<br>ファイターズ</td>
  </tr>
  <tr>  
    <td class="no-line"> </td>
    <td class="no-line"> </td>
    <td class="no-line"> </td>
    <td class="no-line"> </td> 
  </tr>
</table>
</section>

<section id="sixth-block">
  <div class="game-list">
    <a href="#">結果発表</a>
    <div class="dropdown__lists">
      <div class="dropdown__list2">1位 鎖骨ぽっきんず</div>
      <div class="dropdown__list2">2位 松浦板倉研</div>
      <div class="dropdown__list2">3位 裏拳ファイターズ</div>
    </div>
  </div>
</section>

<section id="seventh-block">
  <div class="blue">
    <%= link_to 'トップページ', :controller => "top", :action => "index" %>
  </div>
  <div class="blue">
    <%= link_to '次の試合へ', :controller =>"schedule",:action =>"result20240304" %>
  </div>
</section>


  
</body>


</html>

app/views/top/index.html.erb
<%= stylesheet_link_tag 'top', :media => "all" %>
<header>
</header>
<div id="first-block">
    <div class="bg-image1">
        <div class="bg-inner">
            <div class="upp">        
                <%= link_to '生物学科公式スポーツ大会', :controller => "top", :action => "index" %>
            </div>
            <div class="nogawa">
                NOGAWA 
                <br>
                CUP
            </div>
        </div>
    </div>
</div>

<section id="second-block">
    <div class="title-name">
        UPCOMING EVENT
    </div>

    <div class="event-day">
        <div class="day">
            4.31
        </div>
        <div class="type">
            Footsal
        </div>
    </div>

    <div class="join">
        <%= link_to 'join', :controller => "members", :action => "new" %>
    </div>
</section>

<section id="third-section">
    <div class="title">
        生物学科では公式スポーツ大会を開催しています！
    </div>

    <div class="sports-container">
        <div class="sports">  
            <%= image_tag 'footsal1.jpg', class:"logo-image" %>
            <div class="sports-name"> 
                Footsal
            </div>
        </div>
            
        <div class="sports">
            <%= image_tag 'baseball1.jpg', class:"logo-image" %>
            <div class="sports-name">
                Baseball
            </div>
        </div>
            
        <div class="sports">
            <%=image_tag 'bad1.jpg',class:"logo-image" %>
            <div class="sports-name">
                Badminton
            </div>
        </div>
    </ul>
</section>

<section id="forth-block">
    <div class="action-title">
        <%= link_to '写真を投稿する', :controller => "photos", :action => "new" %>
        </br>
        </br>
        <%= link_to '写真を見る', :controller => "photos", :action => "index" %>
    </div>
        
    <%=image_tag 'koke.jpg',class:"photo-image" %>

</section>

<section id="fifth-block">
    <div class="schedule-title">
        <br>
        3.4 Footsal  <%=link_to "結果を見る",:controller=>"schedule",:action=>"result20240304" %>
        </br>
        </br>
        2.30 Badminton  <%=link_to "結果を見る",:controller=>"schedule",:action=>"result2024XXXX" %>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
           
    </div>
    <%=image_tag 'note.jpg',class:"note-image" %>
</section>

<section id="logout">
    <% if user_signed_in? %>
        <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
        <div class="blue">
            <%= link_to "ログイン", new_user_session_path %>
            <%= link_to "新規登録", new_user_registration_path %>
        </div>
    <% end %>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>